"""`eap deploy` packaging."""

from __future__ import annotations

import os
import zipfile
from pathlib import Path
from typing import Any, Literal

Runtime = Literal["aws", "gcp", "agentcore", "vertex-agent-engine"]

_DOCKERFILE_TEMPLATE = """\
FROM python:3.11-slim
WORKDIR /app
COPY . /app
RUN pip install --no-cache-dir eap-core && pip install --no-cache-dir .
ENV PYTHONUNBUFFERED=1
CMD ["python", "agent.py"]
"""

_CLOUDBUILD_TEMPLATE = """\
steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/{service}:latest", "."]
  - name: gcr.io/cloud-builders/docker
    args: ["push", "gcr.io/$PROJECT_ID/{service}:latest"]
images:
  - "gcr.io/$PROJECT_ID/{service}:latest"
"""

# AgentCore Runtime expects an ARM64 container on 0.0.0.0:8080 implementing
# the HTTP protocol contract: POST /invocations, GET /ping, optional WS /ws.
# See: https://docs.aws.amazon.com/bedrock-agentcore/latest/devguide/runtime-http-protocol-contract.html
_AGENTCORE_DOCKERFILE = """\
# syntax=docker/dockerfile:1
# AgentCore Runtime requires ARM64 containers; build with --platform linux/arm64.
FROM --platform=linux/arm64 python:3.11-slim
WORKDIR /app
COPY . /app
RUN pip install --no-cache-dir eap-core fastapi 'uvicorn[standard]' \\
    && pip install --no-cache-dir .
ENV PYTHONUNBUFFERED=1
EXPOSE 8080
CMD ["python", "handler.py"]
"""

_AGENTCORE_HANDLER = '''\
"""AgentCore Runtime HTTP protocol handler.

Generated by `eap deploy --runtime agentcore`. Wraps the user's agent
entry point to satisfy the AgentCore HTTP protocol contract:
- POST /invocations  → call the entry function with the prompt
- GET  /ping         → healthcheck
- (Optional) WS /ws  → not implemented by default; add if needed

Entry point: {entry}
"""
{header_warning}
from __future__ import annotations

import asyncio
import importlib.util
import inspect
import sys
import time
from pathlib import Path
from typing import Any

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
{auth_imports}

def _load_entry(spec: str):
    """Load an entry of the form `path.py:func` or `module:func`."""
    if ":" not in spec:
        raise RuntimeError(f"entry must be 'path:function', got: {{spec!r}}")
    target, func = spec.split(":", 1)
    p = Path(target)
    if p.suffix == ".py":
        mod_spec = importlib.util.spec_from_file_location(p.stem, p)
        if mod_spec is None or mod_spec.loader is None:
            raise ImportError(f"could not load {{target}}")
        # Ensure the project's directory is on sys.path so local imports work.
        sys.path.insert(0, str(p.resolve().parent))
        module = importlib.util.module_from_spec(mod_spec)
        sys.modules[mod_spec.name] = module
        mod_spec.loader.exec_module(module)
    else:
        module = importlib.import_module(target)
    if not hasattr(module, func):
        raise AttributeError(f"{{target}} has no attribute {{func!r}}")
    return getattr(module, func)


_entry_callable = _load_entry({entry!r})

app = FastAPI(title="eap-core agent on agentcore")
{auth_wiring}

class InvocationRequest(BaseModel):
    prompt: str


class InvocationResponse(BaseModel):
    response: str
    status: str = "success"


class PingResponse(BaseModel):
    status: str
    time_of_last_update: int


@app.post("/invocations", response_model=InvocationResponse)
async def invocations(
    req: InvocationRequest,{claims_param}
) -> InvocationResponse:
    try:
        result: Any = _entry_callable(req.prompt)
        if inspect.isawaitable(result):
            result = await result
    except Exception as e:  # noqa: BLE001
        raise HTTPException(status_code=500, detail=str(e)) from e
    return InvocationResponse(response=str(result))


@app.get("/ping", response_model=PingResponse)
async def ping() -> PingResponse:
    return PingResponse(status="Healthy", time_of_last_update=int(time.time()))


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=8080)  # noqa: S104
'''

_AGENTCORE_HANDLER_AUTH_IMPORTS = (
    "from fastapi import Depends\n"
    "from eap_core.integrations.agentcore import InboundJwtVerifier, jwt_dependency\n"
)

_AGENTCORE_HANDLER_AUTH_WIRING = """\

_verifier = InboundJwtVerifier(
    discovery_url={discovery_url!r},
    issuer={issuer!r},
    allowed_audiences={audiences!r},
)
_auth_dep = jwt_dependency(_verifier)
"""

_AGENTCORE_HANDLER_UNAUTH_WARNING = """\
# WARNING: This handler runs WITHOUT authentication.
# Pass --auth-discovery-url + --auth-issuer + --auth-audience to wire jwt_dependency.
"""

_AGENTCORE_README = """\
# Agent packaged for AWS Bedrock AgentCore Runtime

This directory was generated by `eap deploy --runtime agentcore`. It
contains an ARM64 Docker container that implements the AgentCore
HTTP protocol contract.

## Authentication

`eap deploy --runtime agentcore` refuses to scaffold an unauthenticated
handler. Pass the OIDC details so `handler.py` wires
`InboundJwtVerifier` + `jwt_dependency` into `POST /invocations`:

```bash
eap deploy --runtime agentcore \\
    --auth-discovery-url https://<your-idp>/.well-known/openid-configuration \\
    --auth-issuer        https://<your-idp> \\
    --auth-audience      my-agent
```

To skip auth wiring for local smoke testing **only**, pass
`--allow-unauthenticated`. The generated handler will then ship without
auth and a `WARNING` comment is emitted at the top of `handler.py`. Do
not use this in production.

## Build the image

```bash
cd dist/agentcore
docker buildx build --platform linux/arm64 -t my-agent:latest .
```

## Push to ECR

```bash
ECR_REGISTRY=<account>.dkr.ecr.us-east-1.amazonaws.com
aws ecr get-login-password --region us-east-1 \\
    | docker login --username AWS --password-stdin "$ECR_REGISTRY"
docker tag my-agent:latest "$ECR_REGISTRY/my-agent:latest"
docker push "$ECR_REGISTRY/my-agent:latest"
```

## Register with AgentCore Runtime

Use the AWS console or:

```bash
aws bedrock-agentcore create-runtime \\
    --name my-agent \\
    --container-uri <account>.dkr.ecr.us-east-1.amazonaws.com/my-agent:latest
```

## Local test

```bash
docker buildx build --platform linux/arm64 -t my-agent:latest --load .
docker run --rm -p 8080:8080 my-agent:latest
# In another terminal:
curl http://localhost:8080/ping
curl -X POST http://localhost:8080/invocations \\
     -H 'Authorization: Bearer <token>' \\
     -H 'Content-Type: application/json' \\
     -d '{"prompt": "hello"}'
```
"""


def _real_deploy_enabled() -> bool:
    return os.environ.get("EAP_ENABLE_REAL_DEPLOY") == "1"


def package_aws(project: Path, *, dry_run: bool = False) -> Path:
    out = project / "dist"
    target = out / "agent.zip"
    if dry_run:
        return target
    out.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(target, "w", zipfile.ZIP_DEFLATED) as zf:
        for src in project.rglob("*"):
            if not src.is_file():
                continue
            rel = src.relative_to(project)
            if rel.parts and rel.parts[0] in {"dist", ".venv", "__pycache__", ".eap"}:
                continue
            zf.write(src, str(rel))
    return target


def package_gcp(project: Path, *, service: str = "eap-agent", dry_run: bool = False) -> Path:
    out = project / "dist" / "agent"
    if dry_run:
        return out
    out.mkdir(parents=True, exist_ok=True)
    (out / "Dockerfile").write_text(_DOCKERFILE_TEMPLATE)
    (out / "cloudbuild.yaml").write_text(_CLOUDBUILD_TEMPLATE.format(service=service))
    # Stage source alongside Dockerfile for image build.
    for src in project.rglob("*"):
        if not src.is_file():
            continue
        rel = src.relative_to(project)
        if rel.parts and rel.parts[0] in {"dist", ".venv", "__pycache__", ".eap"}:
            continue
        target = out / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(src.read_bytes())
    return out


def upload_aws(zip_path: Path, bucket: str) -> str:
    """Real upload via boto3. Gated by EAP_ENABLE_REAL_DEPLOY=1."""
    import boto3  # lazy

    s3 = boto3.client("s3")
    key = f"eap-agents/{zip_path.name}"
    s3.upload_file(str(zip_path), bucket, key)
    return f"s3://{bucket}/{key}"


def deploy_gcp(target_dir: Path, service: str) -> str:
    """Real deploy via gcloud subprocess. Gated by EAP_ENABLE_REAL_DEPLOY=1."""
    import subprocess

    cmd = ["gcloud", "run", "deploy", service, "--source", str(target_dir)]
    subprocess.run(cmd, check=True)  # noqa: S603
    return f"projects/$PROJECT/services/{service}"


def _render_agentcore_handler(entry: str, auth: dict[str, Any] | None) -> str:
    """Render the AgentCore handler template with optional auth wiring.

    ``auth`` is either ``None`` (allow-unauthenticated path) or a dict
    of the form::

        {"discovery_url": str, "issuer": str, "audiences": list[str]}
    """
    if auth is not None:
        header_warning = ""
        auth_imports = _AGENTCORE_HANDLER_AUTH_IMPORTS
        auth_wiring = _AGENTCORE_HANDLER_AUTH_WIRING.format(
            discovery_url=auth["discovery_url"],
            issuer=auth["issuer"],
            audiences=list(auth["audiences"]),
        )
        claims_param = "\n    claims: dict = Depends(_auth_dep),"
    else:
        header_warning = "\n" + _AGENTCORE_HANDLER_UNAUTH_WARNING
        auth_imports = ""
        auth_wiring = ""
        claims_param = ""
    return _AGENTCORE_HANDLER.format(
        entry=entry,
        header_warning=header_warning,
        auth_imports=auth_imports,
        auth_wiring=auth_wiring,
        claims_param=claims_param,
    )


def package_agentcore(
    project: Path,
    *,
    entry: str = "agent.py:answer",
    auth: dict[str, Any] | None = None,
    dry_run: bool = False,
) -> Path:
    """Package the project for AWS Bedrock AgentCore Runtime.

    Produces an ARM64 Docker context at ``dist/agentcore/`` with a
    ``Dockerfile``, a generated ``handler.py`` that satisfies the
    AgentCore HTTP protocol contract, a deploy ``README.md``, and a
    copy of the user's source files.

    When ``auth`` is provided (``{"discovery_url": str, "issuer": str,
    "audiences": list[str]}``), the generated handler wires
    :class:`~eap_core.integrations.agentcore.InboundJwtVerifier` +
    :func:`~eap_core.integrations.agentcore.jwt_dependency` into
    ``POST /invocations``. When ``auth`` is ``None`` the handler is
    emitted without auth and prefixed with a loud warning comment;
    this mode is only safe for local smoke testing.
    """
    out = project / "dist" / "agentcore"
    if dry_run:
        return out
    out.mkdir(parents=True, exist_ok=True)
    (out / "Dockerfile").write_text(_AGENTCORE_DOCKERFILE)
    (out / "handler.py").write_text(_render_agentcore_handler(entry, auth))
    (out / "README.md").write_text(_AGENTCORE_README)
    # Stage source alongside Dockerfile.
    for src in project.rglob("*"):
        if not src.is_file():
            continue
        rel = src.relative_to(project)
        if rel.parts and rel.parts[0] in {"dist", ".venv", "__pycache__", ".eap"}:
            continue
        target = out / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(src.read_bytes())
    return out


def deploy_agentcore(target_dir: Path, *, name: str, region: str) -> str:
    """Real deploy: build, push to ECR, register with AgentCore.

    Gated by EAP_ENABLE_REAL_DEPLOY=1. The path is intentionally minimal
    (subprocess to docker + aws CLI) — full automation lives in a future
    phase.
    """
    import subprocess

    image = f"{name}:latest"
    subprocess.run(  # noqa: S603
        [  # noqa: S607  # docker is on PATH for users who opt in
            "docker",
            "buildx",
            "build",
            "--platform",
            "linux/arm64",
            "--load",
            "-t",
            image,
            str(target_dir),
        ],
        check=True,
    )
    return image  # caller still has to ECR-push + create-runtime; doc covers it


# ---------------------------------------------------------------------------
# Vertex Agent Engine packaging
# ---------------------------------------------------------------------------
#
# Vertex Agent Engine accepts several artifact formats: pickled Python,
# source tarball, Dockerfile, pre-built container image URI, or git
# repository. Container image is the most universal — same approach
# we take for AgentCore — but Vertex doesn't require ARM64 like AgentCore
# Runtime does, so we default to linux/amd64. Users can override via
# --platform if their Vertex region prefers ARM64.

_VERTEX_DOCKERFILE = """\
# syntax=docker/dockerfile:1
# Vertex Agent Engine accepts standard linux/amd64 containers.
# Override with --platform on `docker buildx build` if ARM64 is preferred.
FROM --platform=linux/amd64 python:3.11-slim
WORKDIR /app
COPY . /app
RUN pip install --no-cache-dir eap-core fastapi 'uvicorn[standard]' \\
    && pip install --no-cache-dir .
ENV PYTHONUNBUFFERED=1
ENV PORT=8080
EXPOSE 8080
CMD ["python", "handler.py"]
"""

_VERTEX_HANDLER = '''\
"""Vertex Agent Engine HTTP handler.

Generated by `eap deploy --runtime vertex-agent-engine`. Wraps the
user's agent entry point to satisfy the Cloud Run convention that
Vertex Agent Runtime uses: PORT environment variable, /invocations
for the agent call, /health for the readiness check.

Entry point: {entry}
"""
{header_warning}
from __future__ import annotations

import asyncio
import importlib.util
import inspect
import os
import sys
import time
from pathlib import Path
from typing import Any

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
{auth_imports}

def _load_entry(spec: str):
    """Load an entry of the form ``path.py:func`` or ``module:func``."""
    if ":" not in spec:
        raise RuntimeError(f"entry must be 'path:function', got: {{spec!r}}")
    target, func = spec.split(":", 1)
    p = Path(target)
    if p.suffix == ".py":
        mod_spec = importlib.util.spec_from_file_location(p.stem, p)
        if mod_spec is None or mod_spec.loader is None:
            raise ImportError(f"could not load {{target}}")
        sys.path.insert(0, str(p.resolve().parent))
        module = importlib.util.module_from_spec(mod_spec)
        sys.modules[mod_spec.name] = module
        mod_spec.loader.exec_module(module)
    else:
        module = importlib.import_module(target)
    if not hasattr(module, func):
        raise AttributeError(f"{{target}} has no attribute {{func!r}}")
    return getattr(module, func)


_entry_callable = _load_entry({entry!r})

app = FastAPI(title="eap-core agent on vertex-agent-engine")
{auth_wiring}

class InvocationRequest(BaseModel):
    prompt: str


class InvocationResponse(BaseModel):
    response: str
    status: str = "success"


class HealthResponse(BaseModel):
    status: str
    time_of_last_update: int


@app.post("/invocations", response_model=InvocationResponse)
async def invocations(
    req: InvocationRequest,{claims_param}
) -> InvocationResponse:
    try:
        result: Any = _entry_callable(req.prompt)
        if inspect.isawaitable(result):
            result = await result
    except Exception as e:  # noqa: BLE001
        raise HTTPException(status_code=500, detail=str(e)) from e
    return InvocationResponse(response=str(result))


@app.get("/health", response_model=HealthResponse)
async def health() -> HealthResponse:
    return HealthResponse(status="OK", time_of_last_update=int(time.time()))


if __name__ == "__main__":
    import uvicorn

    port = int(os.environ.get("PORT", "8080"))
    uvicorn.run(app, host="0.0.0.0", port=port)  # noqa: S104
'''

_VERTEX_HANDLER_AUTH_IMPORTS = (
    "from fastapi import Depends\n"
    "from eap_core.integrations.agentcore import InboundJwtVerifier, jwt_dependency\n"
)

_VERTEX_HANDLER_AUTH_WIRING = """\

_verifier = InboundJwtVerifier(
    discovery_url={discovery_url!r},
    issuer={issuer!r},
    allowed_audiences={audiences!r},
)
_auth_dep = jwt_dependency(_verifier)
"""

_VERTEX_HANDLER_UNAUTH_WARNING = """\
# WARNING: This handler runs WITHOUT authentication.
# Pass --auth-discovery-url + --auth-issuer + --auth-audience to wire jwt_dependency.
"""

_VERTEX_README = """\
# Agent packaged for GCP Vertex AI Agent Engine

This directory was generated by `eap deploy --runtime vertex-agent-engine`.
It contains an x86_64 Docker container that follows the Cloud Run
convention (PORT env var, `/health` readiness check, `/invocations`
agent endpoint).

## Authentication

`eap deploy --runtime vertex-agent-engine` refuses to scaffold an
unauthenticated handler. Pass the OIDC details so `handler.py` wires
`InboundJwtVerifier` + `jwt_dependency` into `POST /invocations`:

```bash
eap deploy --runtime vertex-agent-engine \\
    --auth-discovery-url https://<your-idp>/.well-known/openid-configuration \\
    --auth-issuer        https://<your-idp> \\
    --auth-audience      my-agent
```

To skip auth wiring for local smoke testing **only**, pass
`--allow-unauthenticated`. The generated handler will then ship without
auth and a `WARNING` comment is emitted at the top of `handler.py`. Do
not use this in production.

## Build the image

```bash
cd dist/vertex-agent-engine
docker buildx build --platform linux/amd64 -t my-agent:latest .
```

## Push to Artifact Registry

```bash
REGION=us-central1
PROJECT=my-gcp-project
REPO=agents

gcloud artifacts repositories create $REPO \\
    --repository-format=docker --location=$REGION || true

docker tag my-agent:latest \\
    $REGION-docker.pkg.dev/$PROJECT/$REPO/my-agent:latest

gcloud auth configure-docker $REGION-docker.pkg.dev
docker push $REGION-docker.pkg.dev/$PROJECT/$REPO/my-agent:latest
```

## Register with Vertex Agent Engine

Use the Python SDK:

```python
from google.cloud import aiplatform

aiplatform.init(project="my-gcp-project", location="us-central1")

remote_agent = aiplatform.AgentEngine.create(
    display_name="my-agent",
    container_uri="us-central1-docker.pkg.dev/my-gcp-project/agents/my-agent:latest",
)
print("Agent deployed:", remote_agent.resource_name)
```

Or `gcloud beta agent-engines create ...` if you prefer the CLI.

## Local test

```bash
docker buildx build --platform linux/amd64 -t my-agent:latest --load .
docker run --rm -p 8080:8080 -e PORT=8080 my-agent:latest
# In another terminal:
curl http://localhost:8080/health
curl -X POST http://localhost:8080/invocations \\
     -H 'Content-Type: application/json' \\
     -d '{"prompt": "hello"}'
```
"""


def _render_vertex_handler(entry: str, auth: dict[str, Any] | None) -> str:
    """Render the Vertex handler template with optional auth wiring.

    ``auth`` is either ``None`` (allow-unauthenticated path) or a dict
    of the form::

        {"discovery_url": str, "issuer": str, "audiences": list[str]}
    """
    if auth is not None:
        header_warning = ""
        auth_imports = _VERTEX_HANDLER_AUTH_IMPORTS
        auth_wiring = _VERTEX_HANDLER_AUTH_WIRING.format(
            discovery_url=auth["discovery_url"],
            issuer=auth["issuer"],
            audiences=list(auth["audiences"]),
        )
        claims_param = "\n    claims: dict = Depends(_auth_dep),"
    else:
        header_warning = "\n" + _VERTEX_HANDLER_UNAUTH_WARNING
        auth_imports = ""
        auth_wiring = ""
        claims_param = ""
    return _VERTEX_HANDLER.format(
        entry=entry,
        header_warning=header_warning,
        auth_imports=auth_imports,
        auth_wiring=auth_wiring,
        claims_param=claims_param,
    )


def package_vertex_agent_engine(
    project: Path,
    *,
    entry: str = "agent.py:answer",
    auth: dict[str, Any] | None = None,
    dry_run: bool = False,
) -> Path:
    """Package the project for GCP Vertex AI Agent Engine.

    Produces a Docker context at ``dist/vertex-agent-engine/`` with a
    ``Dockerfile``, generated ``handler.py``, deploy ``README.md``,
    and a staged copy of the user's source files. The image targets
    linux/amd64 (Cloud Run-compatible) and exposes a Cloud Run-style
    HTTP contract: ``POST /invocations`` for the agent call,
    ``GET /health`` for readiness checks, ``PORT`` env var honored.

    When ``auth`` is provided (``{"discovery_url": str, "issuer": str,
    "audiences": list[str]}``), the generated handler wires
    :class:`~eap_core.integrations.agentcore.InboundJwtVerifier` +
    :func:`~eap_core.integrations.agentcore.jwt_dependency` into
    ``POST /invocations``. When ``auth`` is ``None`` the handler is
    emitted without auth and prefixed with a loud warning comment;
    this mode is only safe for local smoke testing.
    """
    out = project / "dist" / "vertex-agent-engine"
    if dry_run:
        return out
    out.mkdir(parents=True, exist_ok=True)
    (out / "Dockerfile").write_text(_VERTEX_DOCKERFILE)
    (out / "handler.py").write_text(_render_vertex_handler(entry, auth))
    (out / "README.md").write_text(_VERTEX_README)
    for src in project.rglob("*"):
        if not src.is_file():
            continue
        rel = src.relative_to(project)
        if rel.parts and rel.parts[0] in {"dist", ".venv", "__pycache__", ".eap"}:
            continue
        target = out / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(src.read_bytes())
    return out


def deploy_vertex_agent_engine(
    target_dir: Path,
    *,
    name: str,
    project_id: str,
    region: str,
) -> str:
    """Real deploy: build x86_64 image locally.

    Gated by ``EAP_ENABLE_REAL_DEPLOY=1``. Push to Artifact Registry
    and registration with Vertex Agent Engine are documented in the
    generated README — keeping this helper minimal matches the
    Phase A pattern for AgentCore.
    """
    import subprocess

    image = f"{name}:latest"
    subprocess.run(  # noqa: S603
        [  # noqa: S607
            "docker",
            "buildx",
            "build",
            "--platform",
            "linux/amd64",
            "--load",
            "-t",
            image,
            str(target_dir),
        ],
        check=True,
    )
    return image
