"""`eap publish-to-gateway` scaffolder.

Generates an OpenAPI 3.1 spec from the project's ``@mcp_tool``
registrations so the user can upload it to AWS Bedrock AgentCore
Gateway as an HTTP target. Live registration with the AgentCore API
is gated behind ``EAP_ENABLE_REAL_DEPLOY=1`` (Phase D refinement).
"""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path
from typing import Any


def _load_user_registry(entry: str) -> Any:
    """Import the user's project module by spec; return the registry it populates.

    ``entry`` is a path like ``agent.py`` or ``tools/__init__.py`` —
    importing it triggers the ``@mcp_tool`` decorator side-effect that
    registers tools. We support both styles:

    - new (preferred): the user constructs an explicit ``McpToolRegistry``
      and exposes it on the module as ``REGISTRY`` (the scaffolded
      convention; lowercase ``registry`` is also accepted);
    - legacy: the user's tools call the deprecated ``default_registry()``
      to register, in which case we read it back (suppressing the
      DeprecationWarning emitted by the read since we know it's
      transitional).

    Raises if the module exposes both ``registry`` and ``REGISTRY`` (ambiguous)
    or if the resolved registry is empty (silent zero-tool spec is the worst
    possible failure mode — fail loudly instead).
    """
    import warnings

    p = Path(entry)
    if not p.exists():
        raise FileNotFoundError(f"entry file not found: {entry}")
    sys.path.insert(0, str(p.resolve().parent))
    mod_spec = importlib.util.spec_from_file_location(p.stem, p)
    if mod_spec is None or mod_spec.loader is None:
        raise ImportError(f"could not load {entry}")
    module = importlib.util.module_from_spec(mod_spec)
    sys.modules[mod_spec.name] = module
    mod_spec.loader.exec_module(module)

    has_lower = getattr(module, "registry", None) is not None
    has_upper = getattr(module, "REGISTRY", None) is not None

    if has_lower and has_upper:
        raise RuntimeError(
            f"{entry} exposes both `registry` and `REGISTRY` — pick one "
            f"(REGISTRY is the scaffolded convention)"
        )

    # Prefer the scaffolded convention.
    registry = getattr(module, "REGISTRY", None) or getattr(module, "registry", None)

    if registry is None:
        # Legacy fallback to default_registry() — wrap warning.
        from eap_core.mcp.registry import default_registry

        with warnings.catch_warnings():
            warnings.simplefilter("ignore", DeprecationWarning)
            registry = default_registry()

    if not registry.list_tools():
        raise RuntimeError(
            f"no tools found after importing {entry}: expose an McpToolRegistry "
            f"as `REGISTRY` on the module and register tools onto it explicitly. "
            f"Example:\n"
            f"    REGISTRY = McpToolRegistry()\n"
            f"    REGISTRY.register(my_tool.spec)\n"
        )

    return registry


def publish_to_gateway(
    project: Path,
    *,
    entry: str = "agent.py",
    title: str | None = None,
    server_url: str = "https://your-agent-host.example",
    dry_run: bool = False,
) -> Path:
    """Write an OpenAPI 3.1 spec describing the project's tools.

    Output: ``dist/gateway/openapi.json`` plus a ``README.md`` with
    register-to-Gateway steps. Returns the output directory path.
    """
    out = project / "dist" / "gateway"
    if dry_run:
        return out

    from eap_core.integrations.agentcore import export_tools_as_openapi

    entry_path = (project / entry).resolve()
    registry = _load_user_registry(str(entry_path))
    spec = export_tools_as_openapi(
        registry,
        title=title or project.name,
        version="0.1.0",
        server_url=server_url,
    )

    out.mkdir(parents=True, exist_ok=True)
    (out / "openapi.json").write_text(json.dumps(spec, indent=2) + "\n")
    (out / "README.md").write_text(_README_TEMPLATE.format(project=project.name))
    return out


_README_TEMPLATE = """\
# Publishing {project} tools to AWS Bedrock AgentCore Gateway

This directory was generated by `eap publish-to-gateway`. It contains
an OpenAPI 3.1 spec (`openapi.json`) describing every `@mcp_tool` in
the project as an HTTP operation Gateway can host.

## Upload to Gateway

1. Upload the OpenAPI spec to S3:

   ```bash
   aws s3 cp openapi.json s3://your-bucket/path/openapi.json
   ```

2. Create or update an AgentCore Gateway with this OpenAPI spec as an
   HTTP target. Through the AWS console or:

   ```bash
   aws bedrock-agentcore-control create-gateway-target \\
       --gateway-id <gateway-id> \\
       --target-name {project} \\
       --target-type OPENAPI \\
       --target-uri s3://your-bucket/path/openapi.json
   ```

3. Other agents can now reach these tools through the Gateway URL,
   either as raw MCP HTTP calls or via EAP-Core's `GatewayClient`:

   ```python
   from eap_core.integrations.agentcore import (
       GatewayClient, add_gateway_to_registry,
   )
   from eap_core.mcp import McpToolRegistry

   registry = McpToolRegistry()
   gw = GatewayClient(gateway_url="https://your-gateway.example", identity=nhi)
   specs = await gw.list_tools()
   add_gateway_to_registry(registry, gw, specs)
   # now `client.invoke_tool("<tool_name>", {{...}})` flows through the
   # local middleware chain and forwards to the gateway.
   ```

## Notes

- The spec is regenerated on every `eap publish-to-gateway` run; commit
  it to version control if you want history of the public contract.
- Tools marked `requires_auth=True` are tagged in the spec under
  `x-mcp-tool.requires_auth`; configure Gateway's outbound auth
  accordingly.
"""
